### ISSUE TITLE
Build is failed

### ISSUE THREAD

**Issue by anaspa** [Akagi201/rtmp-push#1]
When I ran make command it shows the error 
"rtmp-push/src/CRtmpStream.h:15:26: fatal error: librtmp/rtmp.h: No such file or directory"

How can we resolve it

**Comment by Akagi201** [comment]
@anaspa put the librtmp source code to /deps/librtmp. It's empty now.

**Comment by anaspa** [comment]
You mean "https://github.com/Akagi201/librtmp"?
After adding this code in librtmp, after that it shows following error

make
[ 50%] Building CXX object CMakeFiles/rtmp_push.dir/src/CRtmpStream.cpp.o
In file included from /home/anas/mytmp/Camera/rtmp/RTMP_PUSH_CPP/rtmp-push/src/CRtmpStream.cpp:10:0:
/home/anas/mytmp/Camera/rtmp/RTMP_PUSH_CPP/rtmp-push/src/bytestream.h:8:8: warning: extra tokens at end of #endif directive [enabled by default]
/home/anas/mytmp/Camera/rtmp/RTMP_PUSH_CPP/rtmp-push/src/CRtmpStream.cpp: In member function ‘int CRtmpStream::SendFlvHeader(unsigned char_, int)’:
/home/anas/mytmp/Camera/rtmp/RTMP_PUSH_CPP/rtmp-push/src/CRtmpStream.cpp:173:68: error: ‘bytestream_get_byte’ was not declared in this scope
/home/anas/mytmp/Camera/rtmp/RTMP_PUSH_CPP/rtmp-push/src/CRtmpStream.cpp:174:68: error: ‘bytestream_get_be24’ was not declared in this scope
/home/anas/mytmp/Camera/rtmp/RTMP_PUSH_CPP/rtmp-push/src/CRtmpStream.cpp: In member function ‘int CRtmpStream::SendFlvFrame(unsigned char_, int)’:
/home/anas/mytmp/Camera/rtmp/RTMP_PUSH_CPP/rtmp-push/src/CRtmpStream.cpp:213:68: error: ‘bytestream_get_byte’ was not declared in this scope
/home/anas/mytmp/Camera/rtmp/RTMP_PUSH_CPP/rtmp-push/src/CRtmpStream.cpp:214:68: error: ‘bytestream_get_be24’ was not declared in this scope
make[2]: **\* [CMakeFiles/rtmp_push.dir/src/CRtmpStream.cpp.o] Error 1
make[1]: **\* [CMakeFiles/rtmp_push.dir/all] Error 2
make: **\* [all] Error 2

**Comment by Akagi201** [comment]
@anaspa You may search the variables to find the definition.

**Comment by anaspa** [comment]
I could  not see any definition on the source. Is it require any other libraries?

**Comment by Akagi201** [comment]
Sorry, maybe the code is missing.......

**Comment by anaspa** [comment]
Can you check it?

**Comment by anaspa** [comment]
We could successfully build the application
